### ISSUE TITLE
Lỗi : System.InvalidOperationException

### ISSUE THREAD

**Issue by thanh10a** [duynguyenfpt/API-Service#2]
Cannot convert object of type 'System.String' to type 'System.Collections.Generic.List`1[CallAttendanceAPIService.Models.Attendance]''

Object phía bên trong JSON vẫn là String -> Phải Convert lần 2

**Comment by duynguyenfpt** [comment]
Fixxed
Tạo thêm 1 object trung gian để lấy String bên trong Object được Parse rồi Parse thêm một lần nữa
